allow-expect-in-tests = true
allow-unwrap-in-tests = true
allow-dbg-in-tests = true
allow-print-in-tests = true
# this crate only exports a couple of constants for coloring
allowed-wildcard-imports = ["simply_colored"]
